// © 2026 行政自動化系統 | Generated by AI Architect | SOP-Compliant
/**
 * ============================================================================
 * 🏢 【場地會辦系統 V2.3.0】（防死鎖單例版）
 * ============================================================================
 * [V2.3.0 更新] 方案 A：新增保全加班系統參數串接與自動超時引導
 * [V2.2.0 更新] 後台衝突單據高亮辨識，支援核准後撤單機制(防呆防錯，並同步淨空行事曆幽靈事件)。
 * [V2.1.2 繼承] 實作單一真相來源防撞：1.前端即時掃描行事曆阻擋 2.背景定時巡邏衝突警告。
 * [V2.1.1 繼承] 新增「指定行事曆ID」設定與靜默容錯降級機制。
 */

// 🟩🟩🟩 【模組一：控制中心 / CONFIG】
const CONFIG = {
  SHEET_REQUESTS: "Requests",
  SHEET_SETTINGS: "System_Settings",
  KEY_PREFIX: "VENUE_SECURE_"
};
const dbSchema = [
  { name: CONFIG.SHEET_REQUESTS, headers: ["單號", "申請時間", "狀態", "姓名", "Email", "單位", "電話", "申請地點", "申請原因", "備註", "時段明細 (JSON)"], color: "#c9daf8" },
  { name: CONFIG.SHEET_SETTINGS, headers: ["設定項目", "設定值", "說明(請勿修改第一欄)"], color: "#d9ead3" }
];

// 🟦🟦🟦 【模組二：分流中心 / GATEWAY】

function onOpen() {
  SpreadsheetApp.getUi().createMenu('🛠️ 場地系統專屬設定')
    .addItem('1️⃣ 一鍵建置資料庫 (初始化)', 'AUTOMATION_SetupDatabase')
    .addSeparator()
    .addItem('🔒 2️⃣ 安全隱藏通關密語', 'AUTOMATION_SecureKeys')
    .addSeparator()
    .addItem('⏱️ 3️⃣ 啟動跨系統衝突巡邏 (每小時)', 'SYS_SetupPatrolTrigger')
    .addToUi();
}

function doGet(e) {
  if (e.parameter.action && e.parameter.id) {
    return SERVICES_HandleAction(e.parameter.action, e.parameter.id);
  }
  return HtmlService.createHtmlOutputFromFile('Index')
    .setTitle('公務使用學校場地會辦系統')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

// 🟨🟨🟨 【模組三：業務邏輯 / SERVICES】

function processForm(formData) {
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(15000);
  } catch (e) { return { success: false, message: "系統目前忙碌中，請稍後再試。" }; }

  try {
    // --- 1. 跨系統防護牆：呼叫 Hub API 驗證 ---
    const verifyRes = TOOLBOX_CallHubApi("verify", formData.email);
    if (!verifyRes || !verifyRes.success || !verifyRes.bound) {
      return { success: false, errorType: "UNBOUND", message: "⚠️ 驗證失敗：您尚未完成本校 LINE 官方帳號綁定。\n\n請先至官方 LINE 進行身分綁定，方可送出申請單！" };
    }

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CONFIG.SHEET_REQUESTS);
    const data = sheet.getDataRange().getValues();

    // --- 2. 防衝突出借檢查 ---
    const requestedLocs = formData.location.split('、').map(l => l.trim());
    const reqEvents = [];
    formData.timeSlots.forEach(slot => {
      const dates = slot.dates.split(', ');
      const startMins = parseInt(slot.startTime.split(':')[0]) * 60 + parseInt(slot.startTime.split(':')[1]);
      const endMins = parseInt(slot.endTime.split(':')[0]) * 60 + parseInt(slot.endTime.split(':')[1]);
      dates.forEach(d => reqEvents.push({ date: d.substring(0, 10), start: startMins, end: endMins, originalDate: d, originalStart: slot.startTime, originalEnd: slot.endTime }));
    });

    for (let i = 1; i < data.length; i++) {
      if (data[i][2] === "已退回" || data[i][2] === "已取消") continue;
      const storedLocs = String(data[i][7] || "").split('、').map(l => l.trim());
      const locOverlap = requestedLocs.filter(l => storedLocs.includes(l));
      if (locOverlap.length > 0 && data[i][10]) {
        for (let sSlot of JSON.parse(data[i][10])) {
          const sStartMins = parseInt(sSlot.startTime.split(':')[0]) * 60 + parseInt(sSlot.startTime.split(':')[1]);
          const sEndMins = parseInt(sSlot.endTime.split(':')[0]) * 60 + parseInt(sSlot.endTime.split(':')[1]);
          for (let sDate of sSlot.dates.split(', ')) {
            const sPureDate = sDate.substring(0, 10);
            for (let reqEv of reqEvents) {
              if (reqEv.date === sPureDate && (reqEv.start < sEndMins && reqEv.end > sStartMins)) {
                return { success: false, message: `【場地衝突】您申請的「${locOverlap.join('、')}」在\n${reqEv.originalDate} ${reqEv.originalStart}~${reqEv.originalEnd}\n已有其他單位預約。` };
              }
            }
          }
        }
      }
    }

    // --- 2.5 外部系統行事曆雙向防撞檢查 ---
    const targetCalId = TOOLBOX_GetConfig("指定行事曆ID");
    if (targetCalId && targetCalId.trim() !== "") {
      try {
        const cal = CalendarApp.getCalendarById(targetCalId.trim());
        if (cal) {
          for (let reqEv of reqEvents) {
            const y = parseInt(reqEv.date.substring(0,4));
            const m = parseInt(reqEv.date.substring(5,7)) - 1;
            const d = parseInt(reqEv.date.substring(8,10));
            const startH = Math.floor(reqEv.start / 60);
            const startM = reqEv.start % 60;
            const endH = Math.floor(reqEv.end / 60);
            const endM = reqEv.end % 60;

            const eventStart = new Date(y, m, d, startH, startM);
            const eventEnd = new Date(y, m, d, endH, endM);

            const existingEvents = cal.getEvents(eventStart, eventEnd);
            for (let ev of existingEvents) {
              const evDesc = ev.getDescription() || "";
              const evLoc = ev.getLocation() || "";

              if (!evDesc.includes("單號: REQ-")) {
                const isLocOverlap = requestedLocs.some(loc => evLoc.includes(loc));
                if (isLocOverlap) {
                   return {
                     success: false,
                     message: `【外部預約衝突】您申請的「${requestedLocs.join('、')}」在\n${reqEv.originalDate} ${reqEv.originalStart}~${reqEv.originalEnd}\n已被外部系統借用 (事件：${ev.getTitle()})。\n\n⚠️ 請更改時間，或至外部預約系統確認！`
                   };
                }
              }
            }
          }
        }
      } catch (e) { console.warn("行事曆外部防撞檢查失敗：" + e.toString()); }
    }

    // --- 3. 資料寫入 ---
    const requestId = `REQ-${Utilities.formatDate(new Date(), "Asia/Taipei", "yyyyMMdd")}-${Math.floor(1000 + Math.random() * 9000)}`;
    const safePhone = formData.phone.startsWith("'") ? formData.phone : "'" + formData.phone;
    sheet.appendRow([requestId, Utilities.formatDate(new Date(), "Asia/Taipei", "yyyy/MM/dd HH:mm:ss"), "待審核", formData.name, formData.email, formData.unit, safePhone, formData.location, formData.reason, formData.remarks || "", JSON.stringify(formData.timeSlots)]);

    // --- 4. 寄出「待審核」Email ---
    const detailTable = TOOLBOX_GenerateDetailTable(requestId, formData, JSON.stringify(formData.timeSlots));
    const scriptUrl = ScriptApp.getService().getUrl();
    const btnStyle = "color:white;padding:12px 18px;text-decoration:none;border-radius:6px;display:inline-block;margin:5px 5px;font-weight:bold;";

    MailApp.sendEmail({
      to: formData.email,
      subject: `[場地申請送出] 單號 ${requestId}`,
      htmlBody: `<h3>${formData.name} 您好，</h3><p>場地申請已送出（目前為待審核）。</p>${detailTable}<br><a href="${scriptUrl}?action=cancel&id=${requestId}" style="background-color:#ef4444;color:white;padding:10px;text-decoration:none;border-radius:5px;">取消申請</a>`
    });

    MailApp.sendEmail({
      to: TOOLBOX_GetConfig("承辦人信箱"),
      subject: `[新場地申請待審核] ${formData.location} - ${formData.name}`,
      htmlBody: `<h3>收到新的場地申請</h3>${detailTable}<br>
        <p><b>請選擇審核動作：</b></p>
        <a href="${scriptUrl}?action=approve_all&id=${requestId}" style="background-color:#16a34a;${btnStyle}">✅ 同意申請 (推播警衛＋申請人)</a><br>
        <a href="${scriptUrl}?action=approve_security&id=${requestId}" style="background-color:#2563eb;${btnStyle}">🛡️ 同意申請 (僅推播警衛)</a><br>
        <a href="${scriptUrl}?action=approve_email&id=${requestId}" style="background-color:#475569;${btnStyle}">📧 同意申請 (僅寄 Email)</a><br>
        <a href="${scriptUrl}?action=reject&id=${requestId}" style="background-color:#ea580c;${btnStyle}">❌ 退回申請</a>`
    });

    return { success: true, message: "表單送出成功！" };
  } catch (error) { return { success: false, message: "錯誤：" + error.toString() };
  } finally { lock.releaseLock(); }
}

/**
 * 處理信件點擊動作 (統一路由) - 支援核准後撤單連動
 */
function SERVICES_HandleAction(action, id) {
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000); 
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(CONFIG.SHEET_REQUESTS);
    const data = sheet.getDataRange().getValues();
    let rowIndex = -1, rowData = null;
    for (let i = 1; i < data.length; i++) {
      if (data[i][0] === id) { rowIndex = i + 1; rowData = data[i]; break; }
    }

    const htmlWrapper = (content) => `<!DOCTYPE html><html lang="zh-TW"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><script src="https://cdn.tailwindcss.com"></script></head><body class="bg-slate-200 min-h-screen flex items-center justify-center p-4 font-sans"><div class="bg-white rounded-2xl shadow-xl p-8 max-w-md w-full text-center">${content}</div></body></html>`;

    if (rowIndex === -1) return HtmlService.createHtmlOutput(htmlWrapper(`<h2 class="text-2xl font-bold text-red-600 mb-4">錯誤</h2><p class="text-slate-600">找不到單號 ${id}</p>`));
    
    const currentStatus = rowData[2];

    // 🛡️ 狀態防護：審核與退回只能在「待審核」時操作
    if (action.startsWith("approve") || action === "reject") {
        if (currentStatus !== "待審核") return HtmlService.createHtmlOutput(htmlWrapper(`<h2 class="text-2xl font-bold text-orange-500 mb-4">狀態異常</h2><p class="text-slate-600">此單號狀態為「${currentStatus}」，無法進行審核操作。</p>`));
    }
    // 🛡️ 狀態防護：取消動作不能在已經失效的狀態下執行
    if (action === "cancel") {
        if (currentStatus === "已退回" || currentStatus === "已取消") return HtmlService.createHtmlOutput(htmlWrapper(`<h2 class="text-2xl font-bold text-orange-500 mb-4">狀態異常</h2><p class="text-slate-600">此單號已處於失效狀態，無法再次取消。</p>`));
    }

    const fakeFormData = { name: rowData[3], unit: rowData[5], phone: rowData[6], location: rowData[7], reason: rowData[8], remarks: rowData[9] };
    const detailTable = TOOLBOX_GenerateDetailTable(id, fakeFormData, rowData[10]);
    const scriptUrl = ScriptApp.getService().getUrl();

    if (action.startsWith("approve")) {
      sheet.getRange(rowIndex, 3).setValue("已同意");
      TOOLBOX_CreateCalendarEvents(rowData);

      const applicantEmail = rowData[4], applicantName = rowData[3], location = rowData[7], securityEmailStr = TOOLBOX_GetConfig("保全人員信箱");
      let resultLog = [];

      // 📧 寄給申請人的核准信 (新增：核准後撤單連結)
      const cancelLink = `${scriptUrl}?action=cancel&id=${id}`;
      MailApp.sendEmail({ 
        to: applicantEmail, 
        subject: `[場地核准] 單號 ${id}`, 
        htmlBody: `
          <p>場地申請<b>已獲核准</b>。</p>${detailTable}
          <br><p>若您的行程有變動需要取消，請點選下方按鈕釋出資源：</p>
          <a href="${cancelLink}" style="background-color:#ef4444;color:white;padding:10px 15px;text-decoration:none;border-radius:5px;display:inline-block;margin-top:10px;">取消申請並刪除行事曆</a>
        ` 
      });
      
      if (securityEmailStr) {
        let icsAttachment = TOOLBOX_CreateICSFile(rowData);
        MailApp.sendEmail({
          to: securityEmailStr, subject: `[保全勤務] 新增場地使用 - ${location}`,
          htmlBody: `<h3>📅 勤務行事曆附件已生成</h3><p>請留意勤務時間與地點。</p>${detailTable}`, attachments: [icsAttachment]
        });
      }
      resultLog.push("Email已發出");

      // LINE 推播...
      const lineMsgApplicant = `✅【場地核准通知】\n單號：${id}\n地點：${location}\n\n您的申請已獲核准並排入行事曆，詳情請收信。`;
      const lineMsgSecurity = `🔔【勤務派發通知】\n地點：${location}\n借用人：${applicantName}\n事由：${rowData[8]}\n單號：${id}\n\n詳細時段請查閱 Email 附件。`;

      if (action === "approve_all") {
        let applicantRes = TOOLBOX_CallHubApi("push", applicantEmail, lineMsgApplicant);
        if(applicantRes && applicantRes.success) resultLog.push("申請人LINE推播成功");
      }

      if (action === "approve_all" || action === "approve_security") {
        if (securityEmailStr) {
          const securityEmailsArray = securityEmailStr.split(',');
          securityEmailsArray.forEach(email => {
            const trimmedEmail = email.trim();
            if (trimmedEmail) {
              let secRes = TOOLBOX_CallHubApi("push", trimmedEmail, lineMsgSecurity);
              if (secRes && secRes.success) resultLog.push(`保全(${trimmedEmail.split('@')[0]}) LINE推播成功`);
            }
          });
        }
      }

      if (action === "approve_email") resultLog.push("已略過 LINE 推播");

      return HtmlService.createHtmlOutput(htmlWrapper(`
        <h2 class="text-3xl font-bold text-green-600 mb-4">✅ 審核完成</h2>
        <p class="text-lg text-slate-700 mb-4">已成功同意該場地申請！</p>
        <div class="bg-slate-50 border border-slate-200 rounded-lg p-4 text-sm text-slate-500 text-left"><strong>系統執行紀錄：</strong><br>${resultLog.join('<br>')}</div>
        <p class="text-slate-400 mt-6 text-sm">您可以直接關閉此視窗。</p>
      `));

    } else if (action === "reject") {
      sheet.getRange(rowIndex, 3).setValue("已退回");
      MailApp.sendEmail({ to: rowData[4], subject: `[申請退回] 單號 ${id}`, htmlBody: `<p>您的場地申請<b>已被退回</b>。</p>${detailTable}` });
      return HtmlService.createHtmlOutput(htmlWrapper(`<h2 class="text-3xl font-bold text-orange-600 mb-4">❌ 已退回</h2><p class="text-slate-600">已成功退回該申請。</p>`));
      
    } else if (action === "cancel") {
      // 💥 核准後撤單連動邏輯
      const prevStatus = currentStatus;
      sheet.getRange(rowIndex, 3).setValue("已取消");
      
      let extraMsg = "";
      if (prevStatus === "已同意") {
          TOOLBOX_DeleteCalendarEvents(id);
          extraMsg = "並已同步刪除行事曆事件";
      }
      
      MailApp.sendEmail({ to: TOOLBOX_GetConfig("承辦人信箱"), subject: `[取消通知] 單號 ${id}`, htmlBody: `<p>申請人已取消申請${extraMsg ? " ("+extraMsg+")" : ""}。</p>${detailTable}` });
      return HtmlService.createHtmlOutput(htmlWrapper(`<h2 class="text-3xl font-bold text-slate-700 mb-4">已取消</h2><p class="text-slate-600">您已成功取消該申請${extraMsg}。</p>`));
    }
  } catch (error) { return HtmlService.createHtmlOutput(`<h3>系統錯誤：${error.message}</h3>`); 
  } finally { lock.releaseLock(); }
}
// 🟧🟧🟧 【模組四：排程與觸發 / AUTOMATION】

function AUTOMATION_SetupDatabase() {
  const ui = SpreadsheetApp.getUi();
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let addedCount = 0;

  dbSchema.forEach(schema => {
    let sheet = ss.getSheetByName(schema.name);
    if (!sheet) {
      sheet = ss.insertSheet(schema.name);
      sheet.appendRow(schema.headers);
      sheet.getRange(1, 1, 1, schema.headers.length).setFontWeight("bold").setBackground(schema.color);
      sheet.setFrozenRows(1);
    }

    if (schema.name === CONFIG.SHEET_SETTINGS) {
      const firstCell = sheet.getRange("A1").getValue();
      if (!String(firstCell).includes("資安警告")) {
        sheet.insertRowBefore(1);
        sheet.getRange("A1:C1").merge().setValue("⚠️ 資安警告：請勿將此試算表共用權限設為「知道連結的任何人均可檢視」，以免金鑰外洩！")
             .setBackground("#ef4444").setFontColor("white").setFontWeight("bold").setHorizontalAlignment("center");
        sheet.setFrozenRows(2);
        sheet.setColumnWidth(1, 200); sheet.setColumnWidth(2, 450); sheet.setColumnWidth(3, 300);
      }

      const defaultSettings = [
        ["HUB_API_URL", "請貼上 LINE Hub 的網頁應用程式網址", "與大腦對接的 API 端點"],
        ["API_SECRET_KEY", "ChungCheng_Secure_123", "必須與 Hub 設定的密語完全一致"],
        ["承辦人信箱", Session.getActiveUser().getEmail(), "接收新申請通知"],
        ["保全人員信箱", "security1@gmail.com, security2@gmail.com", "審核通過後通知勤務 (可填多組，用逗號分隔)"],
        ["場地選項", "前庭廣場,中庭廣場,操場,活動中心,視聽教室,其他", "請以半形逗號分隔"],
        ["單位選項", "教務處,學務處,總務處,輔導室,家長會,志工團,其他", "請以半形逗號分隔"],
        ["開放時間", "08:00-22:00", "限制表單區間"],
        ["指定行事曆ID", "", "請填入目標行事曆ID。若留空或無效，將寫入預設行事曆"],
        ["後台登入密碼", "admin123", "登入網頁戰情室的通關密語"],
        ["加班系統網址", "https://script.google.com/...", "保全加班申請系統的 Web App 網址"],
        ["平日值勤時間", "07:00-21:00", "保全平日上班時段，用於判斷是否需要自動引導加班"],
        ["假日值勤時間", "08:00-20:00", "保全假日上班時段"],
        ["國定假日清單", "2026-04-03,2026-04-04", "國定假日日期，以逗號分隔 (YYYY-MM-DD)"]
      ];

      const existingData = sheet.getDataRange().getValues();
      const existingKeys = existingData.map(row => String(row[0]).trim());

      defaultSettings.forEach(setting => {
        if (!existingKeys.includes(setting[0])) {
          sheet.appendRow(setting);
          addedCount++;
        }
      });
    }
  });

  if (addedCount > 0) ui.alert(`✅ 系統環境掃描完畢！\n已為您自動補齊 ${addedCount} 個遺失的設定項目。`);
  else ui.alert("✅ 系統環境掃描完畢！\n資料庫與設定檔皆完整無缺，無需修復。");
}

function AUTOMATION_SecureKeys() {
  const ui = SpreadsheetApp.getUi();
  const response = ui.alert("🛡️ 隱形保險箱", "即將把通關密語存入系統底層並打上馬賽克。\n確定執行嗎？", ui.ButtonSet.YES_NO);
  if (response !== ui.Button.YES) return;
  try {
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(CONFIG.SHEET_SETTINGS);
    const data = sheet.getDataRange().getValues();
    const props = PropertiesService.getScriptProperties();
    let count = 0;

    data.forEach((row, idx) => {
      const key = String(row[0]).trim();
      const val = String(row[1]).trim();
      if ((key.includes("SECRET") || key.includes("KEY")) && val && !val.includes("***")) {
        props.setProperty(CONFIG.KEY_PREFIX + key, val);
        sheet.getRange(idx + 1, 2).setValue("****** (已安全儲存)").setFontColor("#059669").setFontWeight("bold");
        count++;
      }
    });
    ui.alert(`🛡️ 防護完成！共安全隱藏了 ${count} 組金鑰。`);
  } catch (e) { TOOLBOX_LogError("SecureKeys", e); }
}

function SYS_SetupPatrolTrigger() {
  const ui = SpreadsheetApp.getUi();
  const funcName = 'AUTOMATION_PatrolConflicts';
  const triggers = ScriptApp.getProjectTriggers();
  for (let i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === funcName) {
      ui.alert('⚠️ 跨系統衝突巡邏排程已在執行中，無需重複啟動！');
      return;
    }
  }
  ScriptApp.newTrigger(funcName).timeBased().everyHours(1).create();
  ui.alert('✅ 成功啟動！\n系統將每小時自動在背景掃描共用行事曆，若發現外部預約硬擠，將立即寄信通知承辦人。');
}

function AUTOMATION_PatrolConflicts() {
  const targetCalId = TOOLBOX_GetConfig("指定行事曆ID");
  if (!targetCalId || targetCalId.trim() === "") return;
  
  let cal;
  try { cal = CalendarApp.getCalendarById(targetCalId.trim()); } 
  catch(e) { console.warn("巡邏兵連線行事曆失敗：" + e.toString()); return; }
  if (!cal) return;

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(CONFIG.SHEET_REQUESTS);
  const data = sheet.getDataRange().getValues();
  const adminEmail = TOOLBOX_GetConfig("承辦人信箱");

  for (let i = 1; i < data.length; i++) {
    const status = String(data[i][2] || "").trim();
    const remarks = String(data[i][9] || "");
    
    if ((status === "待審核" || status === "已同意") && !remarks.includes("[已發送衝突警告]")) {
       const reqId = data[i][0];
       const applicant = data[i][3];
       const reqLocs = String(data[i][7] || "").split('、').map(l => l.trim());
       const slots = JSON.parse(data[i][10] || "[]");
       let hasConflict = false;
       let conflictDetails = [];

       for (let slot of slots) {
         const dates = slot.dates.split(', ');
         const startMins = parseInt(slot.startTime.split(':')[0]) * 60 + parseInt(slot.startTime.split(':')[1]);
         const endMins = parseInt(slot.endTime.split(':')[0]) * 60 + parseInt(slot.endTime.split(':')[1]);

         for (let d of dates) {
           const y = parseInt(d.substring(0,4));
           const m = parseInt(d.substring(5,7)) - 1;
           const day = parseInt(d.substring(8,10));
           const startH = Math.floor(startMins / 60);
           const startM = startMins % 60;
           const endH = Math.floor(endMins / 60);
           const endM = endMins % 60;
           const evStart = new Date(y, m, day, startH, startM);
           const evEnd = new Date(y, m, day, endH, endM);

           const events = cal.getEvents(evStart, evEnd);
           for (let ev of events) {
             const evDesc = ev.getDescription() || "";
             const evLoc = ev.getLocation() || "";
             if (!evDesc.includes("單號: REQ-")) {
               const isLocOverlap = reqLocs.some(loc => evLoc.includes(loc));
               if (isLocOverlap) {
                 hasConflict = true;
                 conflictDetails.push(`- 衝突時間: ${d} ${slot.startTime}~${slot.endTime}\n  - 外部事件標題: ${ev.getTitle()}\n  - 外部標記地點: ${evLoc}`);
               }
             }
           }
         }
       }

       if (hasConflict) {
         if (adminEmail) {
           MailApp.sendEmail({
             to: adminEmail,
             subject: `🚨 [跨系統場地衝突警告] 單號 ${reqId}`,
             htmlBody: `
               <h3 style="color: #ef4444;">⚠️ 跨系統場地衝突警告</h3>
               <p>系統背景巡邏兵發現本系統的申請單，與共用行事曆上的「外部預約」發生時間地點重疊！</p>
               <div style="background: #f1f5f9; padding: 15px; border-radius: 8px; margin-bottom: 15px;">
                 <h4 style="margin-top: 0;">📌 本系統已借用資訊：</h4>
                 <ul><li><b>單號:</b> ${reqId} (${status})</li><li><b>申請人:</b> ${applicant}</li><li><b>申請地點:</b> ${reqLocs.join('、')}</li></ul>
               </div>
               <div style="background: #fee2e2; padding: 15px; border-radius: 8px;">
                 <h4 style="margin-top: 0; color: #991b1b;">💥 發現重疊的外部事件：</h4>
                 <pre style="font-family: monospace; white-space: pre-wrap;">${conflictDetails.join('\n\n')}</pre>
               </div>
               <p style="margin-top: 20px;"><b>建議處置：</b><br>請盡速登入外部預約系統確認該筆事件，或聯絡本系統申請人協調取消，以避免現場使用衝突。</p>
             `
           });
         }
         const newRemarks = remarks ? remarks + "\n[已發送衝突警告]" : "[已發送衝突警告]";
         sheet.getRange(i + 1, 10).setValue(newRemarks);
       }
    }
  }
}

// 🛠️🛠️🛠️ 【模組五：核心工具箱 / TOOLBOX】

function TOOLBOX_CallHubApi(action, targetEmail, message = "") {
  const hubUrl = TOOLBOX_GetConfig("HUB_API_URL");
  const secret = TOOLBOX_GetConfig("API_SECRET_KEY");
  if (!hubUrl || !hubUrl.startsWith("http")) return { success: false, error: "Hub URL 未設定" };
  try {
    const options = { method: "post", payload: { action: action, secret: secret, email: targetEmail, message: message }, muteHttpExceptions: true };
    return JSON.parse(UrlFetchApp.fetch(hubUrl, options).getContentText());
  } catch (e) { return { success: false, error: e.toString() }; }
}

function TOOLBOX_GetConfig(key) {
  const secure = PropertiesService.getScriptProperties().getProperty(CONFIG.KEY_PREFIX + key);
  if (secure) return secure;
  const data = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(CONFIG.SHEET_SETTINGS).getDataRange().getValues();
  for (let r of data) { if (r[0] === key) return r[1]; }
  return "";
}

function getSettings() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(CONFIG.SHEET_SETTINGS);
  let settings = { locations: [], units: [], openTime: "08:00-22:00", overtimeUrl: "", weekdayHours: "07:00-21:00", holidayHours: "08:00-20:00", holidays: [] };
  if (!sheet) return settings;
  const data = sheet.getDataRange().getValues();
  for (let i = 1; i < data.length; i++) {
    const k = data[i][0], v = data[i][1];
    if (k === "開放時間" && v) settings.openTime = v.toString().trim();
    if (k === "場地選項" && v) settings.locations = v.toString().split(',').map(s => s.trim()).filter(s => s !== "");
    if (k === "單位選項" && v) settings.units = v.toString().split(',').map(s => s.trim()).filter(s => s !== "");
    if (k === "加班系統網址" && v) settings.overtimeUrl = v.toString().trim();
    if (k === "平日值勤時間" && v) settings.weekdayHours = v.toString().trim();
    if (k === "假日值勤時間" && v) settings.holidayHours = v.toString().trim();
    if (k === "國定假日清單" && v) settings.holidays = v.toString().split(',').map(s => s.trim().replace(/\//g, '-')).filter(s => s !== "");
  }
  return settings;
}

function TOOLBOX_GenerateDetailTable(id, fd, slotsJsonStr) {
  let slotsHtml = "<ul>";
  JSON.parse(slotsJsonStr).forEach(s => { slotsHtml += `<li>日期：${s.dates} | 時間：${s.startTime} ~ ${s.endTime}</li>`; });
  slotsHtml += "</ul>";
  return `
    <table border="1" cellpadding="5" style="border-collapse:collapse;width:100%;max-width:600px;">
      <tr><th width="30%" align="left" style="background-color:#f1f5f9;">單號</th><td>${id}</td></tr>
      <tr><th align="left" style="background-color:#f1f5f9;">申請人</th><td>${fd.name} (${fd.unit})</td></tr>
      <tr><th align="left" style="background-color:#f1f5f9;">聯絡電話</th><td>${fd.phone}</td></tr>
      <tr><th align="left" style="background-color:#f1f5f9;">地點</th><td>${fd.location}</td></tr>
      <tr><th align="left" style="background-color:#f1f5f9;">事由</th><td>${fd.reason}</td></tr>
      <tr><th align="left" style="background-color:#f1f5f9;">備註</th><td>${fd.remarks || "無"}</td></tr>
      <tr><th align="left" style="background-color:#f1f5f9;">時段</th><td>${slotsHtml}</td></tr>
    </table>`;
}

function TOOLBOX_CreateCalendarEvents(r) {
  let cal = null;
  const targetCalId = TOOLBOX_GetConfig("指定行事曆ID");
  if (targetCalId && targetCalId.trim() !== "") {
    try { cal = CalendarApp.getCalendarById(targetCalId.trim()); } catch (e) {}
  }
  if (!cal) cal = CalendarApp.getDefaultCalendar();

  const title = `[${r[7]}] ${r[3]} (${r[5]})`;
  const desc = `單號: ${r[0]}\n電話: ${r[6]}\n原因: ${r[8]}\n備註: ${r[9] || "無"}`;
  
  JSON.parse(r[10]).forEach(slot => {
    slot.dates.split(', ').forEach(d => {
      const pureDate = d.substring(0, 10);
      const start = new Date(`${pureDate}T${slot.startTime}:00`);
      const end = new Date(`${pureDate}T${slot.endTime}:00`);
      const ev = cal.createEvent(title, start, end, { description: desc, location: r[7] });
      ev.addPopupReminder(1440); ev.addPopupReminder(720); ev.addPopupReminder(60);
    });
  });
}

// 💥 新增：智慧行事曆淨化引擎
function TOOLBOX_DeleteCalendarEvents(requestId) {
  let cal = null;
  const targetCalId = TOOLBOX_GetConfig("指定行事曆ID");
  if (targetCalId && targetCalId.trim() !== "") {
    try { cal = CalendarApp.getCalendarById(targetCalId.trim()); } catch (e) {}
  }
  if (!cal) cal = CalendarApp.getDefaultCalendar();

  // 掃描前後一年的範圍，尋找該單號的所有幽靈事件
  const now = new Date();
  const start = new Date(now.getFullYear() - 1, now.getMonth(), now.getDate());
  const end = new Date(now.getFullYear() + 2, now.getMonth(), now.getDate());
  
  const events = cal.getEvents(start, end, {search: requestId});
  let deletedCount = 0;
  events.forEach(ev => {
    if (ev.getDescription().includes(requestId)) {
      ev.deleteEvent();
      deletedCount++;
    }
  });
  console.log(`已成功刪除 ${deletedCount} 筆與 ${requestId} 相關的行事曆事件`);
}

function TOOLBOX_CreateICSFile(r) {
  const title = `[${r[7]}] ${r[3]} (${r[5]})`, desc = `單號: ${r[0]}\\n電話: ${r[6]}\\n原因: ${r[8]}`;
  let ics = "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//中正國小//場地系統//EN\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nX-WR-CALNAME:勤務行事曆\r\n";
  const now = Utilities.formatDate(new Date(), "GMT", "yyyyMMdd'T'HHmmss'Z'");
  JSON.parse(r[10]).forEach((slot, i) => {
    slot.dates.split(', ').forEach((d, j) => {
      const [y, m, day] = d.substring(0, 10).split('-');
      const start = new Date(y, parseInt(m) - 1, day, slot.startTime.split(':')[0], slot.startTime.split(':')[1]);
      const end = new Date(y, parseInt(m) - 1, day, slot.endTime.split(':')[0], slot.endTime.split(':')[1]);
      ics += "BEGIN:VEVENT\r\n";
      ics += `UID:${r[0]}-${i}-${j}@chungcheng.kh.edu.tw\r\nDTSTAMP:${now}\r\n`;
      ics += `DTSTART:${Utilities.formatDate(start, "GMT", "yyyyMMdd'T'HHmmss'Z'")}\r\nDTEND:${Utilities.formatDate(end, "GMT", "yyyyMMdd'T'HHmmss'Z'")}\r\n`;
      ics += `SUMMARY:${title}\r\nDESCRIPTION:${desc.replace(/\n/g, '\\n')}\r\nLOCATION:${r[7]}\r\n`;
      ics += "BEGIN:VALARM\r\nACTION:DISPLAY\r\nDESCRIPTION:Reminder\r\nTRIGGER:-PT1440M\r\nEND:VALARM\r\nBEGIN:VALARM\r\nACTION:DISPLAY\r\nDESCRIPTION:Reminder\r\nTRIGGER:-PT720M\r\nEND:VALARM\r\nBEGIN:VALARM\r\nACTION:DISPLAY\r\nDESCRIPTION:Reminder\r\nTRIGGER:-PT60M\r\nEND:VALARM\r\nEND:VEVENT\r\n";
    });
  });
  ics += "END:VCALENDAR\r\n";
  return Utilities.newBlob(ics, 'text/calendar', `${r[0]}-勤務行事曆.ics`);
}

function TOOLBOX_LogError(mod, err) { console.error(`[${mod} Error]: ${err}`); }

// ----------------------------------------------------------------------------
// 📊 【管理後台與戰情室專用 API】
// ----------------------------------------------------------------------------

function API_VerifyAdmin(pwd) {
  const realPwd = TOOLBOX_GetConfig("後台登入密碼");
  return pwd === realPwd || (realPwd === "" && pwd === "admin123");
}

function API_GetDashboardData(pwd) {
  if (!API_VerifyAdmin(pwd)) throw new Error("無效的密碼或登入已過期");

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const reqSheet = ss.getSheetByName(CONFIG.SHEET_REQUESTS);
  const reqData = reqSheet.getDataRange().getValues();
  const now = new Date().getTime();
  const oneDayMs = 24 * 60 * 60 * 1000;

  let validRequests = [];

  for (let i = reqData.length - 1; i > 0; i--) {
    const row = reqData[i];
    let slots = [];
    try { slots = JSON.parse(row[10] || "[]"); } catch(e) {}

    let maxEndTimeMs = 0;
    let minStartTimeMs = Infinity;
    let firstSlotStr = ""; 
    let totalSlotCount = 0; 

    slots.forEach(slot => {
      slot.dates.split(', ').forEach(d => {
        const pureDate = d.substring(0, 10);
        const endMs = new Date(`${pureDate}T${slot.endTime}:00`).getTime();
        if (endMs > maxEndTimeMs) maxEndTimeMs = endMs;
        const startMs = new Date(`${pureDate}T${slot.startTime}:00`).getTime();
        if (startMs < minStartTimeMs) minStartTimeMs = startMs;
        if (totalSlotCount === 0) firstSlotStr = `${pureDate} | ${slot.startTime} ~ ${slot.endTime}`;
        totalSlotCount++;
      });
    });

    if (maxEndTimeMs > 0 && (maxEndTimeMs + oneDayMs) < now) {
      reqSheet.deleteRow(i + 1); 
    } else {
      const currentStatus = String(row[2] || "").trim();
      const remarksStr = String(row[9] || "");
      
      // 🛡️ 新增：解析是否有衝突標記，並派發給前端
      const hasConflict = remarksStr.includes("[已發送衝突警告]");

      if (currentStatus === "待審核" || currentStatus === "已同意") {
        let submitTimeStr = row[1] instanceof Date ? Utilities.formatDate(row[1], "Asia/Taipei", "yyyy/MM/dd HH:mm:ss") : String(row[1] || "");
        let summary = firstSlotStr;
        if (totalSlotCount > 1) summary += " <span class='text-xs font-bold bg-white bg-opacity-70 px-2 py-0.5 rounded-full ml-1'>(多時段)</span>";
        else if (totalSlotCount === 0) summary = "無有效時段";

        validRequests.push({
          id: String(row[0] || ""),
          submitTime: submitTimeStr,
          status: currentStatus,
          name: String(row[3] || ""),
          email: String(row[4] || ""),
          unit: String(row[5] || ""),
          phone: String(row[6] || ""),
          location: String(row[7] || ""),
          reason: String(row[8] || ""),
          remarks: remarksStr,
          slotsHtml: TOOLBOX_GenerateSlotsHtml(slots),
          timeSummary: summary, 
          sortTime: minStartTimeMs === Infinity ? 0 : minStartTimeMs,
          hasConflict: hasConflict // 傳遞給前端作為變色判斷依據
        });
      }
    }
  }

  validRequests.sort((a, b) => a.sortTime - b.sortTime);

  const setSheet = ss.getSheetByName(CONFIG.SHEET_SETTINGS);
  const setValues = setSheet.getDataRange().getValues();
  const settings = [];
  
  for (let i = 0; i < setValues.length; i++) {
    const key = String(setValues[i][0] || "").trim();
    if (key === "" || key.includes("⚠️") || key === "設定項目") continue;
    settings.push({ key: key, value: String(setValues[i][1] || ""), desc: String(setValues[i][2] || "") });
  }

  return { requests: validRequests, settings: settings };
}

function TOOLBOX_GenerateSlotsHtml(slots) {
  if (!slots || slots.length === 0) return "<span class='text-slate-400'>無時段資料</span>";
  let html = '<ul class="list-disc pl-5 space-y-1 text-sm">';
  slots.forEach(s => { html += `<li>${s.dates} | ${s.startTime} ~ ${s.endTime}</li>`; });
  html += '</ul>';
  return html;
}

function API_SaveSettings(pwd, newSettings) {
  if (!API_VerifyAdmin(pwd)) throw new Error("無效的密碼或登入已過期");
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(CONFIG.SHEET_SETTINGS);
  const props = PropertiesService.getScriptProperties();
  const data = sheet.getDataRange().getValues();

  newSettings.forEach(newSet => {
    const key = newSet.key.trim();
    let val = newSet.value.trim();
    let rowIndex = -1;
    for (let i = 1; i < data.length; i++) {
      if (String(data[i][0]).trim() === key) { rowIndex = i + 1; break; }
    }
    if (rowIndex !== -1) {
      if ((key.includes("SECRET") || key.includes("KEY") || key.includes("密碼")) && val) {
        if (!val.includes("***")) {
          props.setProperty(CONFIG.KEY_PREFIX + key, val);
          const masked = val.length > 8 ? val.substring(0, 4) + "***" + val.substring(val.length - 4) : "***(已安全儲存)";
          sheet.getRange(rowIndex, 2).setValue(masked).setFontColor("#059669").setFontWeight("bold");
        }
      } else {
        sheet.getRange(rowIndex, 2).setValue(val).setFontColor("#000000").setFontWeight("normal");
      }
    }
  });
  return "✅ 設定儲存成功！系統已更新。";
}

// 💥 新增：戰情室專屬的「一鍵撤銷與刪除行事曆」API
function API_CancelRequest(pwd, id) {
  if (!API_VerifyAdmin(pwd)) throw new Error("無效的密碼或登入已過期");
  
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CONFIG.SHEET_REQUESTS);
    const data = sheet.getDataRange().getValues();
    
    let rowIndex = -1;
    let currentStatus = "";
    for (let i = 1; i < data.length; i++) {
      if (data[i][0] === id) { 
        rowIndex = i + 1; 
        currentStatus = data[i][2]; 
        break; 
      }
    }

    if (rowIndex === -1) throw new Error("找不到該單號");
    if (currentStatus === "已退回" || currentStatus === "已取消") throw new Error("該單據已處於失效狀態，無法再次撤銷");

    // 更新狀態
    sheet.getRange(rowIndex, 3).setValue("已取消");

    // 若原狀態為已同意，啟動行事曆淨化引擎
    let msg = "✅ 撤單成功！單據狀態已更新為「已取消」。";
    if (currentStatus === "已同意") {
      TOOLBOX_DeleteCalendarEvents(id);
      msg = "✅ 撤單成功！單據已取消，並已自動淨化行事曆上相關的幽靈事件。";
    }

    return msg;
  } finally {
    lock.releaseLock();
  }
}