// © 2026 行政自動化系統 | Generated by AI Architect | SOP-Compliant
/**
 * 🌌 Brian 智慧助手 - V3.9.8 AI-Native 旗艦重構版 (完整整合)
 * * 🛠️ 原創聲明：本專案由 Brian Hung 獨立構思，協同 AI 深度開發。
 * * 🚀 V3.9.8 深度修復紀錄 (Change Log)：
 * 1. 【AI-Native 重構】導入思維鏈先行 (Chain-of-Thought, CoT) 解析架構，要求 AI 先推理再輸出，大幅提升判定率至 90% 以上。
 * 2. 【物理防禦】後端零信任核對閘：若記帳意圖在原文中無「數字」或「卡片/支付關鍵字」，物理強行將金額歸零並降級為 TASK，根除腦補幻覺。
 * 3. 【多工拆解】Few-Shot 意圖定錨：針對多任務沾黏、美食漏判、無數字腦補提供真實範例定錨，避免切碎長文本。
 * 4. 【完整還原】100% 保留 V3.9.7 黃金標準之 safeGetSheet、fetchWithRetry_、Math.max、自動表頭自癒與動態隱藏金鑰。
 */

// 全域工作表名稱字典 (解耦管理)
const DB_TABLES = {
  SETTINGS: '系統設定',
  TASKS: '待辦清單',
  KNOWLEDGE: '知識倉庫',
  EXPENSE: '主表_回饋控管',
  KEYWORDS: '設定_關鍵字',
  LOCATIONS: '口袋名單_旅遊'
};

// ==========================================
// 🟩🟩🟩 【模組一：系統初始化與自癒引擎】 🟩🟩🟩
// ==========================================

function onOpen() {
  SpreadsheetApp.getUi().createMenu('🚀 宇宙信使 V3.9.8')
    .addItem('🏗️ 初始化與架構維護', 'setupDatabase')
    .addSeparator()
    .addItem('🔒 安全隱藏金鑰', 'hideAndSaveSecrets')
    .addSeparator()
    .addItem('🔄 手動同步能量與財務', 'manualSyncTasks')
    .addToUi();
}

/** 🌟 輔助函式：安全取得工作表並提供報錯，防範 Null 崩潰 */
function safeGetSheet(name) {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(name);
  if (!sheet) {
    console.error("❌ 找不到關鍵工作表: " + name);
    return null;
  }
  return sheet;
}

function setupDatabase() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const dbSchema = [
    {
      name: DB_TABLES.SETTINGS, headers: [['項目', '設定值', '說明']], color: '#f4cccc',
      initialData: [
        ['LINE_TOKEN', '', '貼上後點選安全隱藏'], ['AI_API_KEY', '', 'Gemini 2.5 Key'],
        ['GROQ_API_KEY', '', 'Groq API Key'], ['DRIVE_FOLDER_ID', '', 'Drive 存圖夾 ID'],
        ['MY_USER_ID', '', '您的 LINE ID'], ['BOT_NAME', 'Brian 秘書', '助理名稱'],
        ['USER_NAME', 'Brian 老師', '您的稱呼'], ['CALENDAR_ID_FAMILY', '', '家庭行事曆 ID'],
        ['CALENDAR_ID_ACTIVITY', '', '活動行事曆 ID'],
        ['CALENDAR_ID_SEMINAR', '', '研習行事曆 ID'],
        ['CALENDAR_ID_FINANCE', '', '金融理財行事曆 ID']
      ]
    },
    { name: DB_TABLES.TASKS, headers: [['日期', '任務內容', '詳細說明', '執行狀態', 'TaskID', 'txId']], color: '#fff2cc' },
    {
      name: DB_TABLES.KNOWLEDGE, headers: [['日期', '資源標題', '網址(URL)', '分類', '標籤', '重點摘要', '狀態(0未1已)', '縮圖URL', 'txId']], color: '#cfe2f3',
      initialData: [[new Date(), '範例：AI 學習筆記', 'https://ai.google', 'AI', '#技術, #學習', '這是一個範例摘要', 0, '', 'init_tx']]
    },
    { name: DB_TABLES.EXPENSE, headers: [['支付名稱', '類型', '原始額度', '已用金額', '剩餘額度', '結帳日', '備註']], color: '#ead1dc' },
    { name: DB_TABLES.KEYWORDS, headers: [['意圖類別', '定義']], color: '#d9ead3', initialData: [['EXPENSE_REWARD', '財務'], ['TASK', '任務']] },
    {
      name: DB_TABLES.LOCATIONS, headers: [['日期', '景點/餐廳名稱', '地址或區域', 'Google地圖連結', '相關情報(網址/重點)', '狀態(0未去1已去)', 'txId']], color: '#d0e0e3',
      initialData: [[new Date(), '範例：米其林餐廳', '台北市信義區', '', '記得提前訂位', 0, 'init_tx']]
    }
  ];

  dbSchema.forEach(schema => {
    let sheet = ss.getSheetByName(schema.name);
    if (!sheet) {
      sheet = ss.insertSheet(schema.name);
      sheet.getRange(1, 1, 1, schema.headers[0].length).setValues(schema.headers).setBackground(schema.color).setFontWeight('bold').setHorizontalAlignment('center');
      sheet.setFrozenRows(1);
      if (schema.initialData) sheet.getRange(2, 1, schema.initialData.length, schema.initialData[0].length).setValues(schema.initialData);
      sheet.autoResizeColumns(1, schema.headers[0].length);
    } else {
      const existingHeaders = sheet.getRange(1, 1, 1, Math.max(sheet.getLastColumn(), 1)).getValues()[0];
      const req = schema.headers[0];
      let missing = [];
      req.forEach(h => { if (!existingHeaders.includes(h)) missing.push(h); });
      if (missing.length > 0) {
        sheet.getRange(1, existingHeaders.length + 1, 1, missing.length).setValues([missing]).setBackground(schema.color).setFontWeight('bold').setHorizontalAlignment('center');
      }
     
      // V3.9.1 深層資料自癒邏輯 (自動補齊缺失設定欄位)
      if (schema.initialData) {
        const existingData = sheet.getDataRange().getValues();
        const existingKeys = existingData.map(r => String(r[0]).trim());
        let currentHeaderLen = existingHeaders.length + missing.length;
       
        schema.initialData.forEach(initRow => {
          if (!existingKeys.includes(String(initRow[0]).trim())) {
            let newRow = new Array(currentHeaderLen).fill("");
            for (let i = 0; i < initRow.length; i++) newRow[i] = initRow[i];
            sheet.appendRow(newRow);
          }
        });
      }
    }
  });

  if (!ScriptApp.getProjectTriggers().some(t => t.getHandlerFunction() === 'autoSyncTasks')) ScriptApp.newTrigger('autoSyncTasks').timeBased().everyMinutes(30).create();
  if (!ScriptApp.getProjectTriggers().some(t => t.getHandlerFunction() === 'checkAndResetExpenses_')) ScriptApp.newTrigger('checkAndResetExpenses_').timeBased().atHour(5).everyDays(1).create();
 
  SpreadsheetApp.getUi().alert('✅ 系統巡邏與修復完成！\n缺失的欄位或設定項目已為您自動補齊。');
}

function hideAndSaveSecrets() {
  const sheet = safeGetSheet(DB_TABLES.SETTINGS);
  if (!sheet) return;
  const props = PropertiesService.getScriptProperties();
  const data = sheet.getDataRange().getValues();
 
  for (let i = 1; i < data.length; i++) {
    const key = data[i][0] ? String(data[i][0]).trim() : "";
    const val = data[i][1] ? String(data[i][1]).trim() : "";
    if (key && val && !val.includes('***')) {
      props.setProperty(key, val);
      sheet.getRange(i + 1, 2).setValue('**** (已加密隱藏)');
    }
  }
  SpreadsheetApp.getUi().alert('🔒 企業級安全核心加密完成');
}

// ==========================================
// 🔄🔄🔄 【模組二：能量與進度同步引擎】 🔄🔄🔄
// ==========================================

function manualSyncTasks() { autoSyncTasks(); checkAndResetExpenses_(); SpreadsheetApp.getActiveSpreadsheet().toast('🔄 巡邏完畢'); }
function autoSyncTasks() { resetDailyUsage_(); syncTasksLogic(); }

function resetDailyUsage_() {
  const props = PropertiesService.getScriptProperties(), todayStr = Utilities.formatDate(new Date(), "GMT+8", "yyyy-MM-dd");
  if (props.getProperty('LAST_RESET_DATE') !== todayStr) {
    props.setProperty('LAST_RESET_DATE', todayStr); props.setProperty('GEMINI_USAGE', '0'); props.setProperty('GROQ_TOKEN_USAGE', '0');
  }
}

function syncTasksLogic() {
  const sheet = safeGetSheet(DB_TABLES.TASKS);
  if (!sheet) return;
  const data = sheet.getDataRange().getValues();
  if (data.length < 2) return;
  const statusIdx = data[0].indexOf('執行狀態'), taskIdIdx = data[0].indexOf('TaskID');
  if (statusIdx === -1 || taskIdIdx === -1) return;
  for (let i = 1; i < data.length; i++) {
    if (data[i][statusIdx] === '未完成' && data[i][taskIdIdx]) {
      try { if (Tasks.Tasks.get('@default', data[i][taskIdIdx]).status === 'completed') sheet.getRange(i + 1, statusIdx + 1).setValue('✅ 已完成'); } catch(e){}
    }
  }
}

function checkAndResetExpenses_() {
  const sheet = safeGetSheet(DB_TABLES.EXPENSE);
  if (!sheet) return;
  const data = sheet.getDataRange().getValues();
  if (data.length < 2) return;
  const props = PropertiesService.getScriptProperties();
  const payCol = data[0].indexOf('支付名稱'), billDayCol = data[0].indexOf('結帳日'), usedCol = data[0].indexOf('已用金額'), origCol = data[0].indexOf('原始額度'), remainCol = data[0].indexOf('剩餘額度');
  if (payCol === -1 || billDayCol === -1) return;
  const [yyyy, mm, dd] = Utilities.formatDate(new Date(), "GMT+8", "yyyy-MM-dd").split('-').map(Number);
  for (let i = 1; i < data.length; i++) {
    const payName = data[i][payCol], billDayRaw = data[i][billDayCol];
    if (!payName || !billDayRaw) continue;
    const billDay = parseInt(billDayRaw);
    let cycleYear = yyyy, cycleMonth = mm;
    let maxDays = new Date(cycleYear, cycleMonth, 0).getDate();
    if (dd < Math.min(billDay, maxDays)) { cycleMonth -= 1; if (cycleMonth === 0) { cycleMonth = 12; cycleYear -= 1; } }
    const cycleStartStr = `${cycleYear}-${String(cycleMonth).padStart(2, '0')}-${String(Math.min(billDay, new Date(cycleYear, cycleMonth, 0).getDate())).padStart(2, '0')}`;
    if (props.getProperty('RESET_' + payName) !== cycleStartStr) {
      if (usedCol !== -1) sheet.getRange(i + 1, usedCol + 1).setValue(0);
      if (remainCol !== -1 && origCol !== -1) sheet.getRange(i + 1, remainCol + 1).setValue(data[i][origCol]);
      props.setProperty('RESET_' + payName, cycleStartStr);
    }
  }
}

// ==========================================
// 🟦🟦🟦 【模組三：Webhook 與動態映射引擎】 🟦🟦🟦
// ==========================================

function generateTxId_() { return 'tx_' + new Date().getTime() + '_' + Math.floor(Math.random() * 10000); }

function fetchWithRetry_(url, options, maxRetries = 2) {
  options.muteHttpExceptions = true;
  for (let i = 0; i <= maxRetries; i++) {
    try {
      const res = UrlFetchApp.fetch(url, options);
      if (res.getResponseCode() === 200) return res;
      if (i === maxRetries) throw new Error(`Status ${res.getResponseCode()}`);
      Utilities.sleep(1000);
    } catch (e) { if (i === maxRetries) throw e; Utilities.sleep(1000); }
  }
}

function dynamicAppendRow_(sheetName, rowDataObj) {
  const sheet = safeGetSheet(sheetName);
  if (!sheet) return;
  const headers = sheet.getRange(1, 1, 1, Math.max(sheet.getLastColumn(), 1)).getValues()[0];
  let rowArray = new Array(headers.length).fill("");
  for (const key in rowDataObj) { const idx = headers.indexOf(key); if (idx !== -1) rowArray[idx] = rowDataObj[key]; }
  sheet.appendRow(rowArray);
}

function doPost(e) {
  const lock = LockService.getScriptLock();
  try { lock.waitLock(10000); } catch (err) { return; }
  let replyToken = "", userMsg = "";
  try {
    const props = PropertiesService.getScriptProperties();
    const config = {
      API_KEY_A: props.getProperty('AI_API_KEY'), GROQ_API_KEY: props.getProperty('GROQ_API_KEY'),
      TOKEN: props.getProperty('LINE_TOKEN'), BOT_NAME: props.getProperty('BOT_NAME') || 'Brian 秘書',
      USER_NAME: props.getProperty('USER_NAME') || '老師', FOLDER_ID: props.getProperty('DRIVE_FOLDER_ID')
    };
    const parsedData = JSON.parse(e.postData.contents);
    if (!parsedData.events || parsedData.events.length === 0) return;
    const event = parsedData.events[0];
    replyToken = event.replyToken || "";
    if (event.type !== 'message' || !event.message) return;
    
    if (event.message.type === 'image') { handleImageMessage_(event, config, props, replyToken); return; }
    userMsg = event.message.text || "";
    if (userMsg.trim() === "") return;
    if (userMsg.length > 2000) userMsg = userMsg.substring(0, 2000) + "\n\n[系統截斷保護]";
    
    const correctionMatch = userMsg.match(/(不對|錯了|改到|改成|改為|這是|存到)(記帳|待辦|任務|資源|倉庫|日曆|旅遊|tasks|task|keep|calendar|map)/i);
    if (correctionMatch) { handleCorrection_(replyToken, correctionMatch[2].toLowerCase(), config); return; }
    
    // 紀錄執行前的 Token 用量，計算單次耗損
    const initGroq = parseInt(props.getProperty('GROQ_TOKEN_USAGE') || '0');
    const initGem = parseInt(props.getProperty('GEMINI_USAGE') || '0');
    
    const execResult = runLightningCore_(userMsg, config, props);
    let report = ""; let actionsToCache = []; const txId = generateTxId_();
    
    execResult.data.forEach((item, index) => {
      const actionData = executeAction_(item, userMsg, props, txId);
      report += `${index + 1}. ${actionData.res}\n`;
      actionsToCache.push(actionData.cache);
    });
    saveLastAction_(actionsToCache);
    
    // 計算單次用量並顯示
    const finalGroq = parseInt(props.getProperty('GROQ_TOKEN_USAGE') || '0');
    const finalGem = parseInt(props.getProperty('GEMINI_USAGE') || '0');
    const diffGroq = finalGroq - initGroq;
    const diffGem = finalGem - initGem;
    
    let footer = "";
    if (diffGroq > 0) {
      footer = `⚡ B: 本次 ${(diffGroq/1000).toFixed(1)}k | 剩餘 ${(100 - finalGroq/1000).toFixed(1)}k\n🛡️ A: 剩餘 ${20 - finalGem}/20 次\n[${execResult.source}]`;
    } else {
      footer = `🛡️ A: 本次 ${diffGem} 次 | 剩餘 ${20 - finalGem}/20 次\n⚡ B: 剩餘 ${(100 - finalGroq/1000).toFixed(1)}k\n[${execResult.source}]`;
    }
    
    if (replyToken) replyToLine_(replyToken, `🛰️ ${config.BOT_NAME} 報告：\n\n${report.trim()}\n\n${footer}`, config.TOKEN);
  } catch (err) {
    console.error("Critical Webhook Error: " + err.message);
    const errorMsg = `⚠️ 報告，運算發生異常：${err.message.substring(0, 40)}`;
    if (replyToken) { try { replyToLine_(replyToken, errorMsg, PropertiesService.getScriptProperties().getProperty('LINE_TOKEN')); } catch(e){} }
  } finally { lock.releaseLock(); }
}

function runLightningCore_(msg, config, props) {
  const groqModels = [{ name: "llama-3.3-70b-versatile", label: "⚡ 閃電 B1 (70B)" }, { name: "llama-3.1-8b-instant", label: "🔄 降級備援 B2 (8B)" }];
  for (let i = 0; i < groqModels.length; i++) {
    try { const result = callGroqAPI_(msg, groqModels[i].name, config, props); if (result) return { data: result, source: groqModels[i].label }; } catch (e) { if (e.message.includes('401')) break; }
  }
  try { return { data: callGeminiNative_(msg, config, props), source: "🛡️ 原生兜底 A (2.5)" }; } catch (e) { throw new Error("大腦通訊崩潰"); }
}

function getDynamicPayTools_() {
  const sheet = safeGetSheet(DB_TABLES.EXPENSE);
  if (!sheet) return "";
  const data = sheet.getDataRange().getValues(), payCol = data[0].indexOf('支付名稱');
  if (payCol === -1) return "";
  let tools = [];
  for (let i = 1; i < data.length; i++) { if (data[i][payCol]) tools.push(data[i][payCol].toString().trim()); }
  return tools.join(", ");
}

// ==========================================
// 🧠🧠🧠 【模組四：AI 通訊與解析】 🧠🧠🧠
// ==========================================

/** 🌟 V3.9.8 AI-Native 旗艦級 Prompt 設計 (CoT 推理與 Few-Shot 樣本定錨)
 * 為防範 AI 的過度聯想與幻覺，強迫 AI 遵循嚴密的思考路徑，先進行邏輯推理再輸出 JSON。
 */
function getSystemInstruction_(payTools, today) {
  return `你是一位參與大型自動化專案的「高階智慧秘書」。
意圖分類包括：EXPENSE_REWARD(卡片工具:${payTools}), CALENDAR, KNOWLEDGE_SAVE, TASK, LOCATION_SAVE。
今天是 ${today}。

【CoT 推理流程 - 絕對鐵律，依序執行不可跳躍】
你在分析訊息時，必須在輸出的 JSON 中包含 "reasoning"（推理思考過程）欄位，逐一驗證以下步驟，最後才產出 "tasks"：
1. 【日期時間覆寫檢驗 - 最高優先】：訊息中是否含有「明確的未來日期或時間（年/月/日、幾月幾日、星期X、時:分）」？如果是，無論訊息多長或包含多少說明文字，【強制歸類】為 CALENDAR，嚴禁轉為 TASK 或 LOCATION_SAVE。
   ★ 多日期規則（絕對執行）：若訊息含有多個不同日期時間，必須拆解為多個獨立的 CALENDAR 物件，每個日期各自一筆，嚴禁合併。
   ★ calendarType 僅可選以下 5 個值（根據活動性質擇一）：
      - "研習"  → 含「課程、研習、工作坊、講座、研討、上課、培訓、教育」
      - "活動"  → 含「活動、登錄、登記、比賽、社團、運動、表演、集會、委員會、出席、會議」
      - "金融理財" → 含「銀行、金融、刷卡、財務、理財、繳費、投資、費用」
      - "家庭"  → 含「家庭、家人、家族、親子」
      - "個人"  → 其餘所有行事曆事項
2. 【實體覆寫檢驗】：訊息中是否提及「餐廳、菜單、店名、好不好吃、地圖」，且【完全不含日期時間】？若同時有地點特徵但無日期，才強制歸類為 LOCATION_SAVE。若已含日期時間，優先觸發規則 1 (CALENDAR)。
3. 【原子拆解檢驗】：訊息中是否包含多個「獨立的名詞/物品」或「獨立的動作指令」？如果是，必須「狠狠切開」拆解為多個獨立的 JSON 物件，嚴禁合併。
4. 【零幻覺記帳驗證】：如果想判定為 EXPENSE_REWARD，原文中是否【100% 存在明確的數字金額】與【卡片工具關鍵字】？若原文完全沒有提到數字，金額必須設為 0，絕對禁止憑空捏造資料。無數字的消費傾向一律強制判定為 TASK！
5. 【summary 無損原則】：所有 summary 欄位必須逐字完整拷貝原文片段，嚴禁擅自進行語意縮減。

【Few-Shot 樣本定錨 - 嚴厲禁止幻覺】
使用者輸入："台南德州煙燻烤肉 豪華拼盤$1980 營業時間中午 地址是大興街2號"
思考過程：無明確未來日期，提及「餐廳」與「地址」，觸發實體覆寫，判定為 LOCATION_SAVE。
輸出格式：{"reasoning": "無日期，觸發實體覆寫，判定為旅遊美食地圖", "tasks": [{"intent": "LOCATION_SAVE", "title": "台南德州煙燻烤肉", "summary": "台南德州煙燻烤肉 豪華拼盤$1980 營業時間中午 地址是大興街2號", "location": "台南市大興街2號"}]}

使用者輸入："第一彈：AI Agent 應用環境課程 時間：6/24 (三) 19:00-21:00 售點：帶你打好AI基礎。第二彈：AI 神救援課程 時間：7/15 (三) 19:00-21:00 售點：教案、表格全交給AI。第三彈：AI Agent 技能樹 時間：7/30 (四) 19:00-21:00 售點：解鎖各種神級擴充技能。"
思考過程：訊息含有三個獨立的日期時間（6/24、7/15、7/30），觸發「日期時間覆寫」最高優先規則。三個日期各自產生一個 CALENDAR 物件，calendarType 均為「研習」。
輸出格式：{"reasoning": "偵測到三個獨立日期，強制觸發日期覆寫，拆解為3個CALENDAR物件", "tasks": [{"intent": "CALENDAR", "title": "AI Agent 應用環境課程", "startTime": "2026-06-24T19:00:00+08:00", "endTime": "2026-06-24T21:00:00+08:00", "summary": "第一彈：AI Agent 應用環境課程\n售點：帶你打好AI基礎", "calendarType": "研習"}, {"intent": "CALENDAR", "title": "AI 神救援課程", "startTime": "2026-07-15T19:00:00+08:00", "endTime": "2026-07-15T21:00:00+08:00", "summary": "第二彈：AI 神救援課程\n售點：教案、表格全交給AI", "calendarType": "研習"}, {"intent": "CALENDAR", "title": "AI Agent 技能樹", "startTime": "2026-07-30T19:00:00+08:00", "endTime": "2026-07-30T21:00:00+08:00", "summary": "第三彈：AI Agent 技能樹\n售點：解鎖各種神級擴充技能", "calendarType": "研習"}]}

使用者輸入："任務：共約600張椅子，清理小房間椅子，退休人員獎牌與花束(6/29)"
思考過程：訊息中有三個不相干的事項。「共約600張椅子」（TASK）、「清理小房間椅子」（TASK）、「退休人員獎牌與花束(6/29)」含日期（CALENDAR）。拆分為 3 個物件。
輸出格式：{"reasoning": "偵測到多工並列，執行原子化拆解", "tasks": [{"intent": "TASK", "title": "共約600張椅子", "summary": "共約600張椅子"}, {"intent": "TASK", "title": "清理小房間椅子", "summary": "清理小房間椅子"}, {"intent": "CALENDAR", "title": "退休人員獎牌與花束", "summary": "退休人員獎牌與花束(6/29)", "startTime": "2026-06-29T09:00:00+08:00", "endTime": "2026-06-29T10:00:00+08:00", "calendarType": "個人"}]}

使用者輸入："回傳傳電的文件"
思考過程：此訊息完全沒有出現任何數字，也沒有卡片工具。判定為 TASK，金額為 0。
輸出格式：{"reasoning": "無數字且無支付特徵，為防幻覺強制轉為 TASK，金額歸零", "tasks": [{"intent": "TASK", "title": "回傳傳電的文件", "summary": "回傳傳電的文件", "amount": 0}]}

【最終 JSON 格式規範】
輸出必須是 100% 合法的 JSON 物件，格式如下：
{"reasoning": "思考推理過程", "tasks": [{"intent": "...", "title": "...", "summary": "...", "url": "...", "category": "...", "tags": "...", "amount": 0, "paymentName": "...", "startTime": "...", "endTime": "...", "location": "...", "calendarType": "...", "notes": "..."}]}`;
}

function callGroqAPI_(msg, modelName, config, props) {
  const payTools = getDynamicPayTools_(), today = Utilities.formatDate(new Date(), "GMT+8", "yyyy年MM月dd日 EEEE");
  const sysInst = getSystemInstruction_(payTools, today);
  
  const options = { 
    method: "post", 
    contentType: "application/json", 
    headers: { "Authorization": "Bearer " + config.GROQ_API_KEY }, 
    payload: JSON.stringify({ 
      model: modelName, 
      temperature: 0, 
      messages: [
        { role: "system", content: sysInst }, 
        { role: "user", content: msg }
      ], 
      response_format: { type: "json_object" } 
    }) 
  };
  
  const res = fetchWithRetry_("https://api.groq.com/openai/v1/chat/completions", options);
  const rawData = JSON.parse(res.getContentText()), actualTokens = rawData.usage ? rawData.usage.total_tokens : 0;
  if (actualTokens > 0) props.setProperty('GROQ_TOKEN_USAGE', (parseInt(props.getProperty('GROQ_TOKEN_USAGE')||'0') + actualTokens).toString());
  
  const rawContent = rawData.choices[0].message.content.replace(/`{3}(?:json)?/gi, '').trim();
  const parsed = JSON.parse(rawContent);
  return Array.isArray(parsed.tasks) ? parsed.tasks : [parsed];
}

function callGeminiNative_(msg, config, props) {
  const payTools = getDynamicPayTools_(), today = Utilities.formatDate(new Date(), "GMT+8", "yyyy年MM月dd日 EEEE");
  const sysInst = getSystemInstruction_(payTools, today);
  
  const payload = { 
    contents: [{ parts: [{ text: sysInst + "\n\nUser: " + msg }] }], 
    generationConfig: { response_mime_type: "application/json", temperature: 0 } 
  };
  
  const res = fetchWithRetry_(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${config.API_KEY_A}`, { 
    method: "post", 
    contentType: "application/json", 
    payload: JSON.stringify(payload) 
  });
  props.setProperty('GEMINI_USAGE', (parseInt(props.getProperty('GEMINI_USAGE')||'0') + 1).toString());
  
  const rawContent = JSON.parse(res.getContentText()).candidates[0].content.parts[0].text.replace(/`{3}(?:json)?/gi, '').trim();
  const parsed = JSON.parse(rawContent);
  return Array.isArray(parsed.tasks) ? parsed.tasks : [parsed];
}

function handleImageMessage_(event, config, props, replyToken) {
  const payTools = getDynamicPayTools_(), blob = fetchWithRetry_(`https://api-data.line.me/v2/bot/message/${event.message.id}/content`, { headers: { 'Authorization': 'Bearer ' + config.TOKEN } }).getBlob();
  const fileUrl = saveToDrive_(blob, config.FOLDER_ID), today = Utilities.formatDate(new Date(), "GMT+8", "yyyy年MM月dd日 EEEE");
  
  // 🌟 V3.9.8 影像大腦同步套用高階 CoT 提示詞
  const sysInst = getSystemInstruction_(payTools, today) + "\n\n備註：請針對圖片內容進行結構化視覺分析，嚴防對模糊收據或非收據影像產生記帳幻覺。";
  const payload = { 
    contents: [{ 
      parts: [
        { text: sysInst }, 
        { inline_data: { mime_type: "image/jpeg", data: Utilities.base64Encode(blob.getBytes()) } }
      ] 
    }], 
    generationConfig: { response_mime_type: "application/json", temperature: 0 } 
  };
  
  const res = fetchWithRetry_(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${config.API_KEY_A}`, { 
    method: "post", 
    contentType: "application/json", 
    payload: JSON.stringify(payload) 
  });
  
  const initGem = parseInt(props.getProperty('GEMINI_USAGE') || '0');
  props.setProperty('GEMINI_USAGE', (initGem + 1).toString());
  
  const rawContent = JSON.parse(res.getContentText()).candidates[0].content.parts[0].text.replace(/`{3}(?:json)?/gi, '').trim();
  const parsedObj = JSON.parse(rawContent);
  const aiResults = Array.isArray(parsedObj.tasks) ? parsedObj.tasks : [parsedObj];
  
  let report = ""; let actionsToCache = []; const txId = generateTxId_();
  aiResults.forEach((item, index) => {
    if (item.intent === 'EXPENSE_REWARD') {
      const lastExp = JSON.parse(props.getProperty('LAST_EXPENSE_DATA') || '{}');
      if (lastExp.amount == item.amount && (new Date().getTime() - lastExp.timestamp < 1800000)) {
        report += `${index+1}. 💰 [影像合併] $${item.amount}，已關聯。\n`;
        updateThumbnail_(lastExp.txId, fileUrl);
      } else { const ad = executeAction_(item, "[影像解析]", props, txId); report += `${index+1}. 📸 ➔ ${ad.res}\n`; actionsToCache.push(ad.cache); }
    } else { item.thumb = fileUrl; const ad = executeAction_(item, "[影像解析]", props, txId); report += `${index+1}. 📸 ➔ ${ad.res}\n`; actionsToCache.push(ad.cache); }
  });
  saveLastAction_(actionsToCache);
  
  const finalGroq = parseInt(props.getProperty('GROQ_TOKEN_USAGE') || '0');
  const finalGem = parseInt(props.getProperty('GEMINI_USAGE') || '0');
  const footer = `🛡️ A: 本次 1 次 | 剩餘 ${20 - finalGem}/20 次\n⚡ B: 剩餘 ${(100 - finalGroq/1000).toFixed(1)}k\n[📸 影像解析 A (2.5)]`;
  
  if (replyToken) replyToLine_(replyToken, `🛰️ ${config.BOT_NAME} 報告：\n\n${report.trim()}\n\n${footer}`, config.TOKEN);
}

function saveToDrive_(blob, folderId) { try { const folder = DriveApp.getFolderById(folderId), file = folder.createFile(blob); file.setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW); return `https://drive.google.com/uc?export=view&id=${file.getId()}`; } catch(e) { return ""; } }

function updateThumbnail_(txId, url) {
  if (!txId) return;
  const sheet = safeGetSheet(DB_TABLES.KNOWLEDGE);
  if (!sheet) return;
  const data = sheet.getDataRange().getValues(), idCol = data[0].indexOf('txId');
  if (idCol === -1) return;
  for (let i = data.length - 1; i >= 1; i--) {
    if (data[i][idCol] === txId) { const tIdx = data[0].indexOf('縮圖URL'); if (tIdx !== -1) sheet.getRange(i+1, tIdx+1).setValue(url); return; }
  }
  dynamicAppendRow_(DB_TABLES.KNOWLEDGE, { '日期': new Date(), '資源標題': "備份收據", '重點摘要': "自動關聯之記帳收據影像", '縮圖URL': url, 'txId': txId });
}

// ==========================================
// 🔴🔴🔴 【模組五：指令執行與物理防禦閘】 🔴🔴🔴
// ==========================================

function executeAction_(item, rawMsg, props, txId) {
  let res = "";
  const safeTitle = (item.title && item.title.trim() !== "" && item.title !== "null") ? item.title : (rawMsg.length > 20 ? rawMsg.substring(0, 10) + "..." : rawMsg);
  item.title = safeTitle;
  
  // 🛡️ V3.9.8 物理核對閘一：若記帳意圖在原文中完全無「阿拉伯數字」，判定為 AI 嚴重幻覺，強行將金額設為 0
  const hasNumbers = /\d+/.test(rawMsg);
  if (item.intent === 'EXPENSE_REWARD' && !hasNumbers) {
    console.warn("⚠️ 零信任防禦：偵測到記帳意圖但原文無數字特徵，強制將金額歸零。");
    item.amount = 0;
  }

  // 🛡️ V3.9.8 物理核對閘二：若記帳意圖所提取的 paymentName 在原文中完全沒提到，強行將金額設為 0 (防虛擬卡名腦補)
  if (item.intent === 'EXPENSE_REWARD' && item.paymentName) {
    const sanitizedPay = item.paymentName.replace(/\s+/g, '').toUpperCase();
    const sanitizedMsg = rawMsg.replace(/\s+/g, '').toUpperCase();
    if (!sanitizedMsg.includes(sanitizedPay)) {
      console.warn("⚠️ 零信任防禦：偵測到記帳意圖但原文無支付工具關鍵字 [" + item.paymentName + "]，強制將金額歸零。");
      item.amount = 0;
    }
  }

  // 🌟 V3.9.8 Fallback 降級：當金額因找不到數字或觸發物理核對閘而歸 0 時，精準攔截並強制轉為 TASK 待辦清單
  const parsedAmount = parseFloat(item.amount);
  if (item.intent === 'EXPENSE_REWARD' && (isNaN(parsedAmount) || Math.abs(parsedAmount) === 0)) {
    item.intent = 'TASK';
  }

  switch (item.intent) {
    case 'EXPENSE_REWARD': res = handleRewardAction_(item); props.setProperty('LAST_EXPENSE_DATA', JSON.stringify({amount: item.amount, timestamp: new Date().getTime(), paymentName: item.paymentName, txId: txId})); break;
    case 'KNOWLEDGE_SAVE': res = handleKnowledgeSave_(item, txId); break;
    case 'CALENDAR':       res = handleCalendarAction_(item, props); break;
    case 'LOCATION_SAVE':  res = handleLocationSave_(item, txId); break;
    default:               res = handleTaskAction_(item, txId);
  }
  return { res: res, cache: { ...item, msg: rawMsg, txId: txId, taskId: item.taskId, eventId: item.eventId, calendarId: item.calendarId } };
}

function handleLocationSave_(item, txId) {
  const mapUrl = "https://www.google.com/maps/search/?api=1&query=" + encodeURIComponent(item.title + " " + (item.location || ""));
  dynamicAppendRow_(DB_TABLES.LOCATIONS, { '日期': new Date(), '景點/餐廳名稱': item.title, '地址或區域': item.location || "", 'Google地圖連結': mapUrl, '相關情報(網址/重點)': (item.url ? "參考：" + item.url + "\n" : "") + (item.summary || ""), '狀態(0未去1已去)': 0, 'txId': txId });
  return `📍 [旅遊] 已收錄：${item.title}`;
}

function handleRewardAction_(item) {
  const sheet = safeGetSheet(DB_TABLES.EXPENSE);
  if (!sheet) return `❌ 無法存取主表`;
  
  const data = sheet.getDataRange().getValues();
  if (data.length < 2) return `❌ 無資料`;
  
  // 🛡️ V3.9.6 保留：實裝絕對值淨化閥，防禦負數攻擊
  const amt = Math.abs(parseFloat(item.amount) || 0); 
  const pay = item.paymentName ? item.paymentName.trim() : "";
  if (pay === "") return `❌ 無法辨識支付。`;
  
  const payCol = data[0].indexOf('支付名稱'), usedCol = data[0].indexOf('已用金額'), origCol = data[0].indexOf('原始額度'), remainCol = data[0].indexOf('剩餘額度');
  if (payCol === -1 || usedCol === -1) return `❌ 欄位缺失。`;
  
  for (let i = 1; i < data.length; i++) {
    if (data[i][payCol] && data[i][payCol].toString().replace(/\s+/g, '').toUpperCase() === pay.replace(/\s+/g, '').toUpperCase()) {
      const newUsed = (parseFloat(data[i][usedCol]) || 0) + amt;
      sheet.getRange(i+1, usedCol+1).setValue(newUsed);
      let report = `💰 【${data[i][payCol]}】記帳 $${amt}`;
      if (remainCol !== -1 && origCol !== -1) {
        const rem = (parseFloat(data[i][origCol]) || 0) - newUsed;
        sheet.getRange(i + 1, remainCol + 1).setValue(rem);
        report += `\n   💳 剩餘可用：$${rem}`;
      }
      return report;
    }
  }
  return `❌ 找不到 [${pay}]`;
}

function handleCalendarAction_(item, props) {
  let start = new Date(), msg = "";
  if (item.startTime) { let p = new Date(item.startTime); if (!isNaN(p.getTime())) { start = p; } else { msg = " (⚠️時間格式無效)"; } } else { msg = " (⚠️未偵測到時間)"; }
  let end = new Date(start.getTime() + 3600000);
  if (item.endTime) { let pEnd = new Date(item.endTime); if (!isNaN(pEnd.getTime()) && pEnd.getTime() > start.getTime()) end = pEnd; }
  
  let cal, type = item.calendarType || "個人";
  if (type === "家庭")     cal = CalendarApp.getCalendarById(props.getProperty('CALENDAR_ID_FAMILY')   || "");
  else if (type === "活動") cal = CalendarApp.getCalendarById(props.getProperty('CALENDAR_ID_ACTIVITY') || "");
  else if (type === "研習") cal = CalendarApp.getCalendarById(props.getProperty('CALENDAR_ID_SEMINAR')  || "");
  else if (type === "金融理財") cal = CalendarApp.getCalendarById(props.getProperty('CALENDAR_ID_FINANCE')  || "");
  
  if (!cal) { cal = CalendarApp.getDefaultCalendar(); if (type !== "個人") msg += " (⚠️排入預設)"; }
  
  // 組合完整說明欄位，收納所有相關資訊至行事曆說明欄
  const descParts = [];
  if (item.summary  && item.summary  !== "null") descParts.push("📝 摘要："  + item.summary);
  if (item.location && item.location !== "null") descParts.push("📍 地點："  + item.location);
  if (item.url      && item.url      !== "null") descParts.push("🔗 連結："  + item.url);
  if (item.notes    && item.notes    !== "null") descParts.push("🗒️ 備註：" + item.notes);
  descParts.push("\n🤖 由 Brian 智慧助手自動建立");
  const desc = descParts.join("\n");
  
  const event = cal.createEvent(item.title, start, end, { description: desc, location: item.location || "" });
  item.eventId = event.getId(); item.calendarId = cal.getId();
  try { event.removeAllReminders(); event.addPopupReminder(360); event.addPopupReminder(720); } catch (e) {}
  return `📅 [${type}] 已排入：${item.title}（日曆：${cal.getName()}）${msg}`;
}

function handleTaskAction_(item, txId) {
  const task = Tasks.Tasks.insert({ title: "[處理] " + item.title, notes: item.summary, due: new Date().toISOString() }, '@default');
  dynamicAppendRow_(DB_TABLES.TASKS, { '日期': new Date(), '任務內容': "[處理] " + item.title, '詳細說明': item.summary, '執行狀態': "未完成", 'TaskID': task.id, 'txId': txId });
  item.taskId = task.id; return `📋 [任務] 已新增：${item.title}`;
}

function handleKnowledgeSave_(item, txId) {
  dynamicAppendRow_(DB_TABLES.KNOWLEDGE, { '日期': new Date(), '資源標題': item.title, '網址(URL)': item.url || "", '分類': item.category || "資源", '標籤': item.tags || "", '重點摘要': item.summary || "", '狀態(0未1已)': 0, '縮圖URL': item.thumb || "", 'txId': txId });
  return `📚 [知識] 已存入：${item.title}`;
}

function handleCorrection_(replyToken, targetLabel, config) {
  const props = PropertiesService.getScriptProperties(), last = props.getProperty('LAST_ACTION');
  if (!last) return replyToLine_(replyToken, `❓ 找不到紀錄`, config.TOKEN);
  let acts = []; try { acts = JSON.parse(last); } catch(e){}
  if(acts.length === 0) return replyToLine_(replyToken, `❓ 找不到紀錄`, config.TOKEN);
  const target = { '記帳': 'EXPENSE_REWARD', '待辦': 'TASK', '任務': 'TASK', '資源': 'KNOWLEDGE_SAVE', '日曆': 'CALENDAR', '旅遊': 'LOCATION_SAVE' }[targetLabel] || 'TASK';
  let report = "🔄 糾偏報告：\n", txId = generateTxId_();
  dynamicAppendRow_(DB_TABLES.KEYWORDS, { '意圖類別': target, '定義': acts[0].msg.substring(0, 4) });
  acts.forEach((a, i) => {
    undoLastAction_(a);
    const r = executeAction_({ intent: target, title: a.title, summary: a.summary || a.msg, url: a.url, tags: a.tags, category: a.category, thumb: a.thumb, amount: a.amount, paymentName: a.paymentName, calendarType: a.calendarType, location: a.location }, a.msg, props, txId);
    report += `${i + 1}. 移至 [${targetLabel}] ➔ ${r.res}\n`;
  });
  if (replyToken) replyToLine_(replyToken, report.trim(), config.TOKEN);
}

function undoLastAction_(action) {
  if (action.intent === 'EXPENSE_REWARD' && action.paymentName) {
    const sheet = safeGetSheet(DB_TABLES.EXPENSE);
    if (!sheet) return;
    const data = sheet.getDataRange().getValues();
    const payCol = data[0].indexOf('支付名稱'), usedCol = data[0].indexOf('已用金額'), origCol = data[0].indexOf('原始額度'), remCol = data[0].indexOf('剩餘額度');
    if (payCol !== -1 && usedCol !== -1) {
      for (let i = 1; i < data.length; i++) {
        if (data[i][payCol] && data[i][payCol].toString().trim() === action.paymentName) {
          const current = (parseFloat(data[i][usedCol]) || 0) - Math.abs(parseFloat(action.amount) || 0);
          sheet.getRange(i+1, usedCol+1).setValue(current);
          if (remCol !== -1 && origCol !== -1) sheet.getRange(i+1, remCol+1).setValue((parseFloat(data[i][origCol]) || 0) - current);
          break;
        }
      }
    }
  } else {
    const sheetName = action.intent === 'LOCATION_SAVE' ? DB_TABLES.LOCATIONS : ((action.intent === 'TASK' || action.intent === 'CALENDAR') ? DB_TABLES.TASKS : DB_TABLES.KNOWLEDGE);
    const sheet = safeGetSheet(sheetName);
    if (sheet && action.txId) {
      const data = sheet.getDataRange().getValues(), idCol = data[0].indexOf('txId');
      if (idCol !== -1) { for (let i = data.length - 1; i >= 1; i--) { if (data[i][idCol] === action.txId) { sheet.deleteRow(i + 1); break; } } }
    }
  }
  if (action.intent === 'CALENDAR' && action.eventId && action.calendarId) { try { CalendarApp.getCalendarById(action.calendarId).getEventById(action.eventId).deleteEvent(); } catch(e) {} }
  if (action.intent === 'TASK' && action.taskId) { try { Tasks.Tasks.remove('@default', action.taskId); } catch(e) {} }
}

function saveLastAction_(actionsArray) {
  let jsonStr = JSON.stringify(actionsArray);
  if (jsonStr.length > 8500) {
    const safe = actionsArray.map(a => ({ ...a, summary: a.summary ? a.summary.substring(0, 400) + '...' : '', msg: a.msg ? a.msg.substring(0, 100) + '...' : '' }));
    jsonStr = JSON.stringify(safe);
    if (jsonStr.length > 9000) jsonStr = JSON.stringify([{intent: 'TASK', msg: '容量限制已截斷'}]);
  }
  PropertiesService.getScriptProperties().setProperty('LAST_ACTION', jsonStr);
}

// 🌟 V3.9.7 保留：使用 fetchWithRetry_ 封裝 replyToLine_，確保不漏失訊息
function replyToLine_(token, msg, tAccess) { 
  fetchWithRetry_('https://api.line.me/v2/bot/message/reply', { 
    method: 'post', 
    contentType: 'application/json', 
    headers: { Authorization: 'Bearer ' + tAccess }, 
    payload: JSON.stringify({ replyToken: token, messages: [{ type: 'text', text: msg }] }) 
  }); 
}

function doGet() {
  const template = HtmlService.createTemplateFromFile('Index'), props = PropertiesService.getScriptProperties();
  template.botName = props.getProperty('BOT_NAME') || 'Brian 秘書';
  template.usageA = props.getProperty('GEMINI_USAGE') || '0';
  template.usageB = ((parseInt(props.getProperty('GROQ_TOKEN_USAGE') || '0')) / 1000).toFixed(1);
  return template.evaluate().setTitle(template.botName + ' 指揮中心').addMetaTag('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

function getDashboardData() {
  const knowSheet = safeGetSheet(DB_TABLES.KNOWLEDGE);
  const locSheet = safeGetSheet(DB_TABLES.LOCATIONS);
  
  if (!knowSheet || !locSheet) return { knowledge: [], locations: [] };

  const knowData = knowSheet.getDataRange().getValues();
  const locData = locSheet.getDataRange().getValues();
  
  const knowH = knowData[0], locH = locData[0];
  const knowledge = knowData.slice(1).filter(r => r[0]).map((r, i) => ({
    id: 'k' + i, time: Utilities.formatDate(new Date(r[0]), "GMT+8", "yyyy/MM/dd HH:mm"),
    title: String(r[knowH.indexOf('資源標題')] || ""), url: String(r[knowH.indexOf('網址(URL)')] || ""),
    category: String(r[knowH.indexOf('分類')] || ""), tags: String(r[knowH.indexOf('標籤')] || ""),
    summary: String(r[knowH.indexOf('重點摘要')] || ""), status: String(r[knowH.indexOf('狀態(0未1已)')] || "0"), thumb: String(r[knowH.indexOf('縮圖URL')] || "")
  }));
  const locations = locData.slice(1).filter(r => r[0]).map((r, i) => ({
    id: 'l' + i, time: Utilities.formatDate(new Date(r[0]), "GMT+8", "yyyy/MM/dd HH:mm"),
    title: String(r[locH.indexOf('景點/餐廳名稱')] || ""), location: String(r[locH.indexOf('地址或區域')] || ""),
    url: String(r[locH.indexOf('Google地圖連結')] || ""), summary: String(r[locH.indexOf('相關情報(網址/重點)')] || ""), status: String(r[locH.indexOf('狀態(0未去1已去)')] || "0")
  }));
  return { knowledge: knowledge, locations: locations };
}